// Gestionnaire d'erreurs asynchrones pour Ã©viter try/catch partout
const asyncHandler = fn => (req, res, next) => {
  Promise.resolve(fn(req, res, next)).catch(next);
};

export default asyncHandler; 